version: "3.8"
services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: 'scheduling_dev'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456789'
      MYSQL_ROOT_PASSWORD: '123456789'
    ports:
      - "3306:3306"
    expose:
      - "3306"
  
  api:
    build:
      context: ./agendamento-backend/
      dockerfile: Dockerfile
    container_name: agendamento-backend
    restart: always
    ports:
      - "3050:3050"
    volumes:
      - "./agendamento-backend/dist/:/home/node/app"
      - "./agendamento-backend/node_modules:/home/node/app/node_modules"
  
  web:
    build:
      context: ./agendamento-frontend/
      dockerfile: Dockerfile
    container_name: agendamento-frontend
    restart: always
    ports:
      - "8080:80"
    volumes:
      - "./agendamento-frontend/build/:/usr/share/nginx/html"